const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { COMPANY_LOGO_DIR } = require('../config/uploadPaths');

function money(n) {
  return `${Number(n).toLocaleString('fr-FR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} MAD`;
}

// company_info.invoice_logo_path is a full public URL (see
// settingsController.js) - the actual file, for pdfkit's own use, is
// just its last path segment, inside COMPANY_LOGO_DIR on this same
// server's filesystem.
function resolveLogoPath(invoiceLogoPath) {
  if (!invoiceLogoPath) return null;
  const filePath = path.join(COMPANY_LOGO_DIR, invoiceLogoPath.split('/').pop());
  return fs.existsSync(filePath) ? filePath : null;
}

function addPartyBlock(doc, x, y, heading, lines) {
  doc.font('Helvetica-Bold').fontSize(9).text(heading, x, y);
  doc.font('Helvetica').fontSize(9);
  let cursorY = y + 14;
  lines.filter(Boolean).forEach((line) => {
    doc.text(line, x, cursorY, { width: 240 });
    cursorY = doc.y + 2;
  });
  return cursorY;
}

// data: { type: 'client'|'supplier', invoiceNumber, dateLabel, monthLabel,
//         company (company_info row), party ({ name, ice, rc, address,
//         email, phone } - client row for type client, just { name } for
//         type supplier since consultants have no legal/business fields),
//         label, totalDays, rate, totalHt, totalTva, totalTtc }
function generateInvoicePdf(data, destinationPath) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const stream = fs.createWriteStream(destinationPath);
    doc.pipe(stream);
    stream.on('finish', resolve);
    stream.on('error', reject);
    doc.on('error', reject);

    const { company } = data;
    const logoPath = resolveLogoPath(company.invoice_logo_path);

    // Header - Handsight's own logo + admin/legal block, always shown
    // (whether Handsight is the issuer or the recipient on this document).
    let headerY = 50;
    if (logoPath) {
      try {
        doc.image(logoPath, 50, headerY, { height: 40 });
      } catch {
        // Corrupt/unreadable image file - skip it, don't fail the whole PDF.
      }
    }
    doc.font('Helvetica-Bold').fontSize(9)
      .text(company.legal_name || 'Handsight Solutions', 300, headerY, { width: 245, align: 'right' });
    doc.font('Helvetica').fontSize(8);
    [
      company.address,
      company.ice ? `ICE: ${company.ice}` : null,
      company.rc ? `RC: ${company.rc}` : null,
      company.tax_identifier ? `IF: ${company.tax_identifier}` : null,
      company.email,
      company.phone
    ].filter(Boolean).forEach((line) => {
      doc.text(line, 300, doc.y, { width: 245, align: 'right' });
    });

    doc.moveDown(2);
    const afterHeaderY = Math.max(doc.y, headerY + 70);

    // Title + invoice metadata
    doc.font('Helvetica-Bold').fontSize(16).text('FACTURE', 50, afterHeaderY);
    doc.font('Helvetica').fontSize(9);
    doc.text(`N°: ${data.invoiceNumber}`, 50, doc.y + 6);
    doc.text(`Date: ${data.dateLabel}`, 50, doc.y + 2);
    doc.text(`Période: ${data.monthLabel}`, 50, doc.y + 2);

    // Party blocks - who is billing whom flips by type. Client invoices:
    // Handsight bills the client. Supplier invoices: framed as the
    // consultant billing Handsight (Handsight is the recipient), even
    // though this PDF is generated by Handsight's own system for its
    // own records.
    const partyY = doc.y + 20;
    if (data.type === 'client') {
      addPartyBlock(doc, 320, partyY, 'Facturé à :', [
        data.party.name,
        data.party.address,
        data.party.ice ? `ICE: ${data.party.ice}` : null,
        data.party.rc ? `RC: ${data.party.rc}` : null,
        data.party.email,
        data.party.phone
      ]);
    } else {
      addPartyBlock(doc, 50, partyY, 'Fournisseur :', [data.party.name]);
      addPartyBlock(doc, 320, partyY, 'Facturé à :', [
        company.legal_name,
        company.address,
        company.ice ? `ICE: ${company.ice}` : null
      ]);
    }

    // Line item table
    let tableY = partyY + 90;
    const col = { desc: 50, qte: 330, pu: 400, montant: 470 };
    doc.font('Helvetica-Bold').fontSize(9);
    doc.text('Description', col.desc, tableY);
    doc.text('Qté (j)', col.qte, tableY);
    doc.text('PU HT', col.pu, tableY);
    doc.text('Montant HT', col.montant, tableY);
    doc.moveTo(50, tableY + 14).lineTo(545, tableY + 14).stroke();

    const rowY = tableY + 20;
    doc.font('Helvetica').fontSize(9);
    doc.text(data.label, col.desc, rowY, { width: 270 });
    doc.text(String(data.totalDays), col.qte, rowY);
    doc.text(money(data.rate), col.pu, rowY);
    doc.text(money(data.totalHt), col.montant, rowY);

    doc.moveTo(50, rowY + 30).lineTo(545, rowY + 30).stroke();

    // Totals
    const totalsY = rowY + 45;
    doc.font('Helvetica').fontSize(9);
    doc.text('Total HT :', 400, totalsY, { width: 80 });
    doc.text(money(data.totalHt), 470, totalsY, { width: 75, align: 'right' });
    doc.text('TVA (20%) :', 400, totalsY + 16, { width: 80 });
    doc.text(money(data.totalTva), 470, totalsY + 16, { width: 75, align: 'right' });
    doc.font('Helvetica-Bold');
    doc.text('Total TTC :', 400, totalsY + 32, { width: 80 });
    doc.text(money(data.totalTtc), 470, totalsY + 32, { width: 75, align: 'right' });

    // Footer - Handsight's own bank details, reference info either way.
    const footerY = totalsY + 80;
    doc.font('Helvetica-Bold').fontSize(8).text('Coordonnées bancaires', 50, footerY);
    doc.font('Helvetica').fontSize(8);
    [
      company.bank_name ? `Banque: ${company.bank_name}` : null,
      company.bank_agency ? `Agence: ${company.bank_agency}` : null,
      company.bank_rib ? `RIB: ${company.bank_rib}` : null,
      company.bank_iban ? `IBAN: ${company.bank_iban}` : null,
      company.bank_swift ? `BIC/SWIFT: ${company.bank_swift}` : null
    ].filter(Boolean).forEach((line) => {
      doc.text(line, 50, doc.y + 2);
    });

    doc.end();
  });
}

module.exports = { generateInvoicePdf };
